### ISSUE TITLE
Adding "install_templates"

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/cloudman-helm#19]
Wanted to capture the conversations @nuwang and I have been having into a more concise issue for whenever we start implementing this.
The basic idea is to have the ability to specify templates for charts at launch time for the CM chart, which would then be the values template used by CM to boot up new charts via the UI.

I believe succinctly the last design we got to is roughly:

```
projman_config:
  projects:
    - name: initial
      launch_templates:
          jupyter:
              values:
                  description: example of an overwrite value for the template installed with the project
 
  install_templates:
    jupyter:
        name: jupyterhub/jupyterhub
        namespace: {{ context.Project }}
        values:
          ingress:
            enabled: true
            path: /{{ context.Project }}/jupyterhub
            hosts:
              - ~
          hub:
            baseUrl: /{{ context.Project }}/jupyterhub
          proxy:
            secretToken: {{ unique_id() }}
 ```

where the install template is evaluated by CM in relation to the context (generated by projman for user/project) along with autogeneration macros (eg for passwords and tokens. Note: can recycle a lot if not all of the templating logic from CM-Boot). The install templates will exist across projects (I would vote to also have the ability to add install_templates in each project configuration so we can have project-specific charts). When launching, the user will also have the ability to add values, similar to the `launch_template` for the auto-deployed charts. Admin users will be able to change all values, project admins should probably be limited to a subset of values: eg, can only change `configs` in Galaxy, maybe also disk space, but not some infrastructure-related values such as image or postgres configuration.

**Comment by nuwang** [comment]
I think the project section could change a bit as follows:
```
projman_config:
  projects:
    initial:
      charts:
          jupyter:
              install_template: jupyter
              values:
                  description: example of an overwrite value for the template install
          jupyter2:
              install_template: jupyter
              values:
                  description: example of an overwrite value for the template install

```
Main changes are that the list of projects is no longer an array, and launch_template was renamed to charts, since that's just the list of charts to install. Calling it `launch_template` suggests that it is itself a reusable template, which it is not?
